In [60]:
import numpy as np
import matplotlib.pyplot as plt

In [70]:

class LinearReg():
    def __init__(self, mean=2, sigma=0.01, m=100, n=10):
        self.mean = mean
        self.sigma = sigma
        self.X = None
        self.m = m
        self.n = n
        self.x = None
        self.y = None
        self.beta = None
        self.gen_data()

    def gen_data(self):
        '''
        Generates matrix X and matrix Y
        '''
        np.random.seed(1234)
        self.X = np.random.normal(self.mean, self.sigma, (self.m,self.n))
        self.x = np.c_[np.ones(100), self.X]
        self.y = np.random.uniform(low=0.0, high=50.0, size=100)
        self.beta = np.zeros(self.n+1)
        
    
    def learn_simple_linreg(self):
        '''
        Applies Gaussian Elimination to find beta vector
        Inspired from this post : https://www.codesansar.com/numerical-methods/gauss-elimination-method-python-program.htm
        '''
        a = self.x[0:12]
        n = self.n 
        x = self.beta
        
        # Gaussian Elimination
        for i in range(n):

            for j in range(i+1, n):
                ratio = a[j][i]/a[i][i]

                for k in range(n+1):
                    a[j][k] = a[j][k] - ratio * a[i][k]

        # Back Substitution
        x[n-1] = a[n-1][n]/a[n-1][n-1]

        for i in range(n-2,-1,-1):
            x[i] = a[i][n]

            for j in range(i+1,n):
                x[i] = x[i] - a[i][j]*x[j]

            x[i] = x[i]/a[i][i]
         
        self.beta = x

    def predict_simple_linreg(self, x):
        y_pred = self.beta * np.transpose(x)
        return y_pred

    def run_pred(self):
        y_preds = []
        for x in self.x:
            y = self.predict_simple_linreg(x)
            y_preds = y_preds + [y]
        return y_preds

    def compute_error(self, y_preds):
        y_preds = np.array(y_preds)
        mse = ((y_preds - self.y) ** 2).mean(axis=0)
        return mse

    def plot_preds(self, y_preds):
        fig = plt.figure(figsize=(6, 6))
        ax = fig.add_subplot(111, projection='3d')
        
        ax.scatter(self.x, self.y, linewidths=1, alpha=.7,
           edgecolor='k',
           s = 200)
        plt.scatter(self.x, y_preds, color="red", label="pred")
        plt.legend(loc="upper left")
        #plt.xlim([1.95,2.05])
        plt.show()

    def numpy_linreg(self):
        #A = np.vstack(self.x).T
        betas = np.zeros(11)
        betas = np.linalg.lstsq(self.x, self.y, rcond=None)[0]
        return betas

    def run_numpy_pred(self, beta_vector):
        y_preds = [beta_vector*x for x in self.x]
        return y_preds

In [69]:
lin_reg = LinearReg()
## Using custom written function

lin_reg.learn_simple_linreg()
y_preds = lin_reg.run_pred()
#lin_reg.plot_preds(y_preds)

[-2.34415982 -0.6956775  -0.56670044 -0.83438113  0.73585167  1.19987536
  0.18168745 -0.15337871  0.31110827  1.99288427  0.        ]


In [68]:
## Using numpy.linalg.lstsq

lin_reg = LinearReg()
betas = lin_reg.numpy_linreg()
lin_reg.run_numpy_pred(betas)

[array([ 484.74136646, -274.45144696,  229.05463588, -407.82778207,
         -95.0346761 , -259.36411657,  563.59195752,  110.43718673,
        -505.38971789, -108.02027205,  284.57803291]),
 array([ 484.74136646, -275.38047162,  231.5696542 , -406.85720662,
         -94.22152231, -259.86716492,  561.10895165,  110.18749294,
        -507.73616839, -108.72529842,  285.57927796]),
 array([ 484.74136646, -273.52860905,  229.67103488, -405.31868064,
         -95.44686376, -262.01755713,  559.78636551,  110.33600046,
        -502.39712139, -107.91290567,  289.32920098]),
 array([ 484.74136646, -273.26138271,  230.81557286, -407.0480375 ,
         -95.68125275, -261.42610646,  560.7604788 ,  110.03313543,
        -506.18502535, -108.46634906,  291.2459719 ]),
 array([ 484.74136646, -273.91035753,  229.77417785, -405.00024712,
         -94.1959547 , -260.62447389,  558.5860217 ,  109.88935248,
        -507.04967893, -108.41976318,  288.11509338]),
 array([ 484.74136646, -274.95740442,  228.76